services:
  # --- Backend: FastAPI (Docker) ---
  - type: web
    name: msme-api
    runtime: docker
    plan: free
    region: oregon
    autoDeploy: true

    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    # If you DID NOT edit Dockerfile CMD to use ${PORT}, uncomment:
    # dockerCommand: bash -lc "uvicorn main:app --host 0.0.0.0 --port ${PORT}"

    healthCheckPath: /healthz

    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: ASYNC_MONGODB_URI
        sync: false
      - key: SPEECH_KEY
        sync: false
      - key: SPEECH_REGION
        sync: false
      - key: SUPPORT_DOC_DB_NAME
        sync: false
      - key: SUPPORT_DOC_COLLECTION
        sync: false

  # --- Frontend: Static Site ---
  - type: web
    name: msme-frontend
    runtime: static
    staticPublishPath: langgraph-chatbot-frontend
    buildCommand: ""     # no build step for pure HTML/JS/CSS
    routes:
      - type: rewrite
        source: /api/*
        destination: https://msme-api.onrender.com/:splat